from __future__ import annotations

from docprod.planning.models import ContentCategory

# Longer phrases first in matching is handled by scoring every term.
CATEGORY_TERMS: dict[ContentCategory, tuple[str, ...]] = {
    ContentCategory.location_establishing: (
        "train station",
        "railway station",
        "platform",
        "station",
        "airport",
        "street",
        "city",
        "town",
        "village",
        "neighborhood",
    ),
    ContentCategory.time_establishing: (
        "morning",
        "evening",
        "night",
        "afternoon",
        "yesterday",
        "hours later",
        "clock",
        "later that",
    ),
    ContentCategory.person: ("man", "woman", "commuter", "passenger", "person"),
    ContentCategory.money: ("money", "cash", "wallet", "bank", "coins", "bills"),
    ContentCategory.police: ("police", "officer", "cop"),
    ContentCategory.crime: ("stolen", "theft", "crime", "abandoned", "suspect"),
    ContentCategory.vehicle: ("train", "car", "bus", "taxi", "drove", "vehicle"),
    ContentCategory.building: ("building", "house", "office", "courthouse"),
    ContentCategory.document: (
        "document",
        "report",
        "record",
        "paper",
        "clipping",
        "tag",
        "evidence",
    ),
    ContentCategory.news: ("newspaper", "headline", "news"),
    ContentCategory.map_or_travel: ("map", "route", "exit", "north", "travel"),
    ContentCategory.technology: ("computer", "laptop", "server", "device"),
    ContentCategory.phone_or_computer: ("phone", "called", "telephone", "laptop", "computer"),
    ContentCategory.court_or_legal: ("court", "legal", "judge", "lawsuit", "lawyer"),
    ContentCategory.nature: ("forest", "river", "tree", "sky", "field"),
    ContentCategory.crowd: ("crowd", "crowded", "people"),
    ContentCategory.interior: ("inside", "interior", "room", "hallway"),
    ContentCategory.action: (
        "ran",
        "run",
        "walked",
        "walk",
        "opened",
        "closed",
        "grabbed",
        "escaped",
        "escape",
        "entered",
        "enter",
        "left",
        "leave",
        "chased",
        "chase",
        "drove",
        "drive",
        "fought",
        "fight",
        "attacked",
        "attack",
    ),
    ContentCategory.danger: ("danger", "threat", "weapon", "gun", "attack"),
    ContentCategory.generic: (),
}

MOTION_STRENGTH: dict[str, int] = {
    # high
    "run": 3,
    "ran": 3,
    "running": 3,
    "sprint": 3,
    "chase": 3,
    "chased": 3,
    "fight": 3,
    "fought": 3,
    "attack": 3,
    "attacked": 3,
    "crash": 3,
    "crashed": 3,
    "escape": 3,
    "escaped": 3,
    # medium
    "drive": 2,
    "drove": 2,
    "grab": 2,
    "grabbed": 2,
    "throw": 2,
    "threw": 2,
    "climb": 2,
    "climbed": 2,
    # low
    "walk": 1,
    "walked": 1,
    "enter": 1,
    "entered": 1,
    "leave": 1,
    "left": 1,
    "open": 1,
    "opened": 1,
    "close": 1,
    "closed": 1,
}

MOTION_TERMS: tuple[str, ...] = tuple(MOTION_STRENGTH)

# Bag/container phrases must not count as document visuals.
DOCUMENT_CONTAINER_PHRASES: tuple[str, ...] = (
    "briefcase",
    "document bag",
    "file bag",
)
