from __future__ import annotations

from docprod.planning.models import ContentCategory

# Longer phrases first in matching is handled by scoring every term.
CATEGORY_TERMS: dict[ContentCategory, tuple[str, ...]] = {
    ContentCategory.location_establishing: (
        "train station",
        "railway station",
        "platform",
        "station",
        "airport",
        "street",
        "city",
        "town",
        "village",
        "neighborhood",
    ),
    ContentCategory.time_establishing: (
        "morning",
        "evening",
        "night",
        "afternoon",
        "yesterday",
        "hours later",
        "clock",
        "later that",
    ),
    ContentCategory.person: ("man", "woman", "commuter", "passenger", "person"),
    ContentCategory.money: ("money", "cash", "wallet", "bank", "coins", "bills"),
    ContentCategory.police: ("police", "officer", "cop"),
    ContentCategory.crime: ("stolen", "theft", "crime", "abandoned", "suspect"),
    ContentCategory.vehicle: ("train", "car", "bus", "taxi", "drove", "vehicle"),
    ContentCategory.building: ("building", "house", "office", "courthouse"),
    ContentCategory.document: (
        "document",
        "report",
        "record",
        "paper",
        "clipping",
        "tag",
        "evidence",
    ),
    ContentCategory.news: ("newspaper", "headline", "news"),
    ContentCategory.map_or_travel: ("map", "route", "exit", "north", "travel"),
    ContentCategory.technology: ("computer", "laptop", "server", "device"),
    ContentCategory.phone_or_computer: ("phone", "called", "telephone", "laptop", "computer"),
    ContentCategory.court_or_legal: ("court", "legal", "judge", "lawsuit", "lawyer"),
    ContentCategory.nature: ("forest", "river", "tree", "sky", "field"),
    ContentCategory.crowd: ("crowd", "crowded", "people"),
    ContentCategory.interior: ("inside", "interior", "room", "hallway"),
    ContentCategory.action: (
        "ran",
        "run",
        "walked",
        "walk",
        "opened",
        "closed",
        "grabbed",
        "escaped",
        "escape",
        "entered",
        "enter",
        "left",
        "leave",
        "chased",
        "chase",
        "drove",
        "drive",
        "fought",
        "fight",
        "attacked",
        "attack",
    ),
    ContentCategory.danger: ("danger", "threat", "weapon", "gun", "attack"),
    ContentCategory.generic: (),
}

MOTION_TERMS: tuple[str, ...] = (
    "run",
    "ran",
    "running",
    "drive",
    "drove",
    "fight",
    "fought",
    "escape",
    "escaped",
    "enter",
    "entered",
    "leave",
    "left",
    "open",
    "opened",
    "close",
    "closed",
    "grab",
    "grabbed",
    "chase",
    "chased",
    "walk",
    "walked",
    "attack",
    "attacked",
)
