from __future__ import annotations

from docprod.planning.models import ContentCategory

CATEGORY_TERMS: dict[ContentCategory, tuple[str, ...]] = {
    ContentCategory.location_establishing: (
        "tren istasyonu",
        "istasyon",
        "peron",
        "şehir",
        "sehir",
        "sokak",
        "cadde",
        "havaalanı",
        "havaalani",
    ),
    ContentCategory.time_establishing: (
        "sabah",
        "akşam",
        "aksam",
        "gece",
        "öğleden",
        "ogleden",
        "saat",
    ),
    ContentCategory.person: ("adam", "kadın", "kadin", "yolcu", "kişi", "kisi"),
    ContentCategory.money: ("para", "banka", "nakit", "cüzdan", "cuzdan"),
    ContentCategory.police: ("polis", "memur"),
    ContentCategory.crime: ("suç", "suc", "hırsız", "hirsiz", "terk edilmiş", "terk edilmis"),
    ContentCategory.vehicle: ("tren", "araba", "otobüs", "otobus", "taksi"),
    ContentCategory.building: ("bina", "ev", "ofis", "mahkeme binası"),
    ContentCategory.document: ("rapor", "evrak", "belge", "kanıt", "kanit", "kupür", "kupur"),
    ContentCategory.news: ("gazete", "haber"),
    ContentCategory.map_or_travel: ("harita", "rota", "çıkış", "cikis", "kuzey"),
    ContentCategory.technology: ("bilgisayar", "sunucu"),
    ContentCategory.phone_or_computer: ("telefon", "aradı", "aradi", "bilgisayar"),
    ContentCategory.court_or_legal: ("mahkeme", "dava", "yasal", "avukat", "tutanak"),
    ContentCategory.nature: ("orman", "nehir", "ağaç", "agac"),
    ContentCategory.crowd: ("kalabalık", "kalabalik"),
    ContentCategory.interior: ("içeri", "iceri", "oda", "koridor"),
    ContentCategory.action: (
        "koş",
        "kos",
        "kaç",
        "kac",
        "sür",
        "sur",
        "girdi",
        "çıktı",
        "cikti",
        "açtı",
        "acti",
        "kapattı",
        "kapatti",
        "yürüdü",
        "yurudu",
        "saldır",
        "saldir",
        "kovala",
        "kovaladı",
        "kovaladi",
        "indi",
        "aldı",
        "aldi",
    ),
    ContentCategory.danger: ("tehlike", "silah", "saldırı", "saldiri"),
    ContentCategory.generic: (),
}

MOTION_TERMS: tuple[str, ...] = (
    "koş",
    "kos",
    "kaç",
    "kac",
    "sür",
    "sur",
    "girdi",
    "çıktı",
    "cikti",
    "açtı",
    "acti",
    "kapattı",
    "kapatti",
    "yürüdü",
    "yurudu",
    "saldır",
    "saldir",
    "kovala",
    "kovaladı",
    "kovaladi",
    "indi",
    "aldı",
    "aldi",
)
