from __future__ import annotations

from docprod.planning.models import ContentCategory

CATEGORY_TERMS: dict[ContentCategory, tuple[str, ...]] = {
    ContentCategory.location_establishing: (
        "tren istasyonu",
        "istasyon",
        "peron",
        "şehir",
        "sehir",
        "sokak",
        "cadde",
        "havaalanı",
        "havaalani",
    ),
    ContentCategory.time_establishing: (
        "sabah",
        "akşam",
        "aksam",
        "gece",
        "öğleden",
        "ogleden",
        "saat",
    ),
    ContentCategory.person: ("adam", "kadın", "kadin", "yolcu", "kişi", "kisi"),
    ContentCategory.money: ("para", "banka", "nakit", "cüzdan", "cuzdan"),
    ContentCategory.police: ("polis", "memur"),
    ContentCategory.crime: ("suç", "suc", "hırsız", "hirsiz", "terk edilmiş", "terk edilmis"),
    ContentCategory.vehicle: ("tren", "araba", "otobüs", "otobus", "taksi"),
    ContentCategory.building: ("bina", "ev", "ofis", "mahkeme binası"),
    ContentCategory.document: (
        "rapor",
        "evrak",
        "belge",
        "dosya",
        "kanıt",
        "kanit",
        "kupür",
        "kupur",
    ),
    ContentCategory.news: ("gazete", "haber"),
    ContentCategory.map_or_travel: ("harita", "rota", "çıkış", "cikis", "kuzey"),
    ContentCategory.technology: ("bilgisayar", "sunucu"),
    ContentCategory.phone_or_computer: ("telefon", "aradı", "aradi", "bilgisayar"),
    ContentCategory.court_or_legal: ("mahkeme", "dava", "yasal", "avukat", "tutanak"),
    ContentCategory.nature: ("orman", "nehir", "ağaç", "agac"),
    ContentCategory.crowd: ("kalabalık", "kalabalik"),
    ContentCategory.interior: ("içeri", "iceri", "oda", "koridor"),
    ContentCategory.action: (
        "koş",
        "kos",
        "kaç",
        "kac",
        "sür",
        "sur",
        "girdi",
        "çıktı",
        "cikti",
        "açtı",
        "acti",
        "kapattı",
        "kapatti",
        "yürüdü",
        "yurudu",
        "saldır",
        "saldir",
        "kovala",
        "kovaladı",
        "kovaladi",
        "indi",
        "aldı",
        "aldi",
    ),
    ContentCategory.danger: ("tehlike", "silah", "saldırı", "saldiri"),
    ContentCategory.generic: (),
}

MOTION_STRENGTH: dict[str, int] = {
    "koş": 3,
    "kos": 3,
    "kaç": 3,
    "kac": 3,
    "kaçan": 3,
    "kacan": 3,
    "kovala": 3,
    "kovaladı": 3,
    "kovaladi": 3,
    "saldır": 3,
    "saldir": 3,
    "saldırı": 3,
    "kavga": 3,
    "çarp": 3,
    "carp": 3,
    "sür": 2,
    "sur": 2,
    "yakala": 2,
    "fırlat": 2,
    "firlat": 2,
    "tırman": 2,
    "tirman": 2,
    "aldı": 2,
    "aldi": 2,
    "yürüdü": 1,
    "yurudu": 1,
    "girdi": 1,
    "çıktı": 1,
    "cikti": 1,
    "açtı": 1,
    "acti": 1,
    "kapattı": 1,
    "kapatti": 1,
    "indi": 1,
}

MOTION_TERMS: tuple[str, ...] = tuple(MOTION_STRENGTH)

DOCUMENT_CONTAINER_PHRASES: tuple[str, ...] = (
    "evrak çantası",
    "evrak cantasi",
    "dosya çantası",
    "dosya cantasi",
)
