from __future__ import annotations

from functools import lru_cache

from docprod.providers.pricing import (
    CLAUDE_OPUS_55_INPUT_USD_PER_MILLION,
    CLAUDE_OPUS_55_OUTPUT_USD_PER_MILLION,
    CLAUDE_OPUS_55_PRICING_SOURCE,
    ELEVEN_MUSIC_USD_PER_MINUTE,
    ELEVEN_SFX_USD_PER_MINUTE,
    ELEVEN_V3_USD_PER_1K_CHARS,
    GPT6_ASTRA_INPUT_USD_PER_MILLION,
    GPT6_ASTRA_OUTPUT_USD_PER_MILLION,
    GPT6_ASTRA_PRICING_SOURCE,
    LYRIA_35_USD_PER_SONG,
    PRICING_AS_OF,
    RUNWAY_ACT_TWO_USD_PER_SEC,
    RUNWAY_GEN45_USD_PER_SEC,
    STORY_TEXT_PRICING_AS_OF,
    VEO_LITE_720P_USD_PER_SEC,
)
from docprod.quality.enums import (
    AdapterStatus,
    CostConfidence,
    Modality,
    ModelReadiness,
    NativeAudioPolicy,
    PriceMode,
    ProductionBackend,
    QualityTier,
)
from docprod.quality.specs import ModelSpec, PricingSpec

KNOWN_TTS_TEXT = PricingSpec(
    mode=PriceMode.PER_TOKEN,
    value=0.60 / 1_000_000,
    unit="text_token_in",
    notes="$0.60/1M text in; audio-out $12/1M when usage present",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="OpenAI TTS usage",
)
KNOWN_WHISPER = PricingSpec(
    mode=PriceMode.PER_MINUTE,
    value=0.006,
    unit="minute",
    notes="OpenAI Whisper $0.006/min",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="OpenAI audio API",
)
KNOWN_VEO_LITE = PricingSpec(
    mode=PriceMode.PER_SECOND,
    value=VEO_LITE_720P_USD_PER_SEC,
    unit="second",
    notes="Veo 3.1 Lite 720p known unit price",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="Google Veo Lite",
)
KNOWN_LYRIA = PricingSpec(
    mode=PriceMode.PER_REQUEST,
    value=LYRIA_35_USD_PER_SONG,
    unit="song",
    notes="Lyria Interactions $0.08/song",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="Google Lyria",
)
KNOWN_GEN45 = PricingSpec(
    mode=PriceMode.PER_SECOND,
    value=RUNWAY_GEN45_USD_PER_SEC,
    unit="second",
    notes="12 credits/s × $0.01",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="https://docs.dev.runwayml.com/guides/pricing/",
)
KNOWN_ACT_TWO = PricingSpec(
    mode=PriceMode.PER_SECOND,
    value=RUNWAY_ACT_TWO_USD_PER_SEC,
    unit="second",
    notes="5 credits/s × $0.01; driving 3–30s",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="https://docs.dev.runwayml.com/guides/pricing/",
)
KNOWN_ELEVEN_TTS = PricingSpec(
    mode=PriceMode.PER_CHARACTER,
    value=ELEVEN_V3_USD_PER_1K_CHARS / 1000.0,
    unit="character",
    notes="$0.10 / 1K characters",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="https://elevenlabs.io/pricing/api",
)
KNOWN_ELEVEN_SFX = PricingSpec(
    mode=PriceMode.PER_MINUTE,
    value=ELEVEN_SFX_USD_PER_MINUTE,
    unit="minute",
    notes="$0.12 / minute",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="https://elevenlabs.io/pricing/api",
)
KNOWN_ELEVEN_MUSIC = PricingSpec(
    mode=PriceMode.PER_MINUTE,
    value=ELEVEN_MUSIC_USD_PER_MINUTE,
    unit="minute",
    notes="$0.15 / minute",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="https://elevenlabs.io/pricing/api",
)
FREE = PricingSpec(
    mode=PriceMode.FREE,
    value=0.0,
    unit="call",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
)
UNKNOWN = PricingSpec(mode=PriceMode.UNKNOWN, confidence=CostConfidence.UNRESOLVED)
GPT6_ASTRA_TEXT = PricingSpec(
    mode=PriceMode.PER_TOKEN,
    value=GPT6_ASTRA_INPUT_USD_PER_MILLION / 1_000_000,
    unit="token",
    notes="$10.00 / 1M input, $50.00 / 1M output (standard API)",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=STORY_TEXT_PRICING_AS_OF,
    source_note=GPT6_ASTRA_PRICING_SOURCE,
    input_usd_per_million=GPT6_ASTRA_INPUT_USD_PER_MILLION,
    output_usd_per_million=GPT6_ASTRA_OUTPUT_USD_PER_MILLION,
)
CLAUDE_OPUS_55_TEXT = PricingSpec(
    mode=PriceMode.PER_TOKEN,
    value=CLAUDE_OPUS_55_INPUT_USD_PER_MILLION / 1_000_000,
    unit="token",
    notes="$4.00 / 1M input, $20.00 / 1M output (standard API)",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=STORY_TEXT_PRICING_AS_OF,
    source_note=CLAUDE_OPUS_55_PRICING_SOURCE,
    input_usd_per_million=CLAUDE_OPUS_55_INPUT_USD_PER_MILLION,
    output_usd_per_million=CLAUDE_OPUS_55_OUTPUT_USD_PER_MILLION,
)
HF_SEEDANCE_25_GEN = PricingSpec(
    mode=PriceMode.PER_SECOND,
    value=0.144,
    unit="second",
    notes="Playground range $0.144–$0.3236/s at 480p–720p; using documented low bound.",
    confidence=CostConfidence.ESTIMATED,
    pricing_as_of="2026-09-27",
    source_note="https://open.higgsfield.ai/models/bytedance/seedance-2.5/video-extend/playground",
)
HF_SEEDANCE_25_EDIT = PricingSpec(
    mode=PriceMode.PER_SECOND,
    value=0.0864,
    unit="second",
    notes="Playground range $0.0864–$0.1942/s for Video Edit / Video Extend.",
    confidence=CostConfidence.ESTIMATED,
    pricing_as_of="2026-09-27",
    source_note="https://open.higgsfield.ai/models/bytedance/seedance-2.5/video-edit/playground",
)
HF_KLING_MOTION = PricingSpec(
    mode=PriceMode.PER_SECOND,
    value=0.084,
    unit="second",
    notes="Kling 3.0 Motion Control (Pro) playground $0.084/s.",
    confidence=CostConfidence.ESTIMATED,
    pricing_as_of="2026-09-27",
    source_note="https://open.higgsfield.ai/models/kling-video/v3.0/4k/text-to-video/playground",
)
HF_KLING_4K_T2V = PricingSpec(
    mode=PriceMode.PER_SECOND,
    value=0.21,
    unit="second",
    notes="Kling 3.0 Text to Video (4K) playground $0.21/s.",
    confidence=CostConfidence.ESTIMATED,
    pricing_as_of="2026-09-27",
    source_note="https://open.higgsfield.ai/models/kling-video/v3.0/4k/text-to-video/playground",
)
HF_GENJUTSU = PricingSpec(
    mode=PriceMode.PER_SECOND,
    value=0.159,
    unit="second",
    notes="Genjutsu Motion Transfer playground $0.159–$0.816/s.",
    confidence=CostConfidence.ESTIMATED,
    pricing_as_of="2026-09-27",
    source_note="https://open.higgsfield.ai/models/workflows/genjutsu/playground",
)


def _m(
    model_id: str,
    provider: str,
    modality: Modality,
    *,
    caps: tuple[str, ...] = (),
    tier: QualityTier = QualityTier.STANDARD,
    speed: str = "unknown",
    pricing: PricingSpec | None = None,
    implemented: bool = False,
    adapter_status: AdapterStatus | None = None,
    async_remote: bool = False,
    local: bool = False,
    notes: str = "",
    display: str = "",
    duration_options: tuple[int, ...] = (),
    min_duration_seconds: float | None = None,
    max_duration_seconds: float | None = None,
    manual_input_required: bool = False,
    implemented_capabilities: tuple[str, ...] = (),
    tested_capabilities: tuple[str, ...] = (),
    input_modalities: tuple[str, ...] = (),
    output_modalities: tuple[str, ...] = (),
    max_reference_images: int | None = None,
    aspect_ratios: tuple[str, ...] = (),
    resolution_options: tuple[str, ...] = (),
    native_audio: bool = False,
    lipsync: bool = False,
    dialogue: bool = False,
    performance_transfer: bool = False,
    identity_consistency_suitability: str = "",
    availability: str = "",
    required_credentials: tuple[str, ...] = (),
    fallbacks: tuple[str, ...] = (),
    close_up_mouth_reliable: bool = False,
    catalog_capabilities: tuple[str, ...] | None = None,
    vendor: str = "",
    model_family: str = "",
    gateway_model_id: str = "",
    readiness: ModelReadiness | None = None,
    native_audio_policy: NativeAudioPolicy | None = None,
    production_backend: ProductionBackend = ProductionBackend.SERVER_API,
) -> ModelSpec:
    status = adapter_status
    if status is None:
        status = AdapterStatus.IMPLEMENTED if implemented else AdapterStatus.CATALOG_ONLY
    avail = availability or ("available" if implemented else "catalog")
    catalog_caps = catalog_capabilities if catalog_capabilities is not None else caps
    if readiness is None:
        if implemented and not manual_input_required:
            readiness = ModelReadiness.PRODUCTION_READY
        elif implemented:
            readiness = ModelReadiness.ADAPTER_IMPLEMENTED
        else:
            readiness = ModelReadiness.CATALOG_ONLY
    audio_policy = native_audio_policy
    if audio_policy is None:
        audio_policy = (
            NativeAudioPolicy.AMBIENT_OPTIONAL if native_audio else NativeAudioPolicy.NONE
        )
    return ModelSpec(
        model_id=model_id,
        provider=provider,
        modality=modality,
        display_name=display or model_id,
        capabilities=caps,
        catalog_capabilities=catalog_caps,
        implemented_capabilities=implemented_capabilities,
        tested_capabilities=tested_capabilities,
        quality_tier=tier,
        speed_tier=speed,
        pricing=pricing or UNKNOWN,
        implemented=implemented,
        adapter_status=status,
        async_remote=async_remote,
        local=local,
        notes=notes,
        duration_options=duration_options,
        min_duration_seconds=min_duration_seconds,
        max_duration_seconds=max_duration_seconds,
        manual_input_required=manual_input_required,
        input_modalities=input_modalities,
        output_modalities=output_modalities,
        max_reference_images=max_reference_images,
        aspect_ratios=aspect_ratios,
        resolution_options=resolution_options,
        native_audio=native_audio,
        lipsync=lipsync,
        dialogue=dialogue,
        performance_transfer=performance_transfer,
        identity_consistency_suitability=identity_consistency_suitability,
        latency_tier=speed,
        availability=avail,
        required_credentials=required_credentials,
        fallbacks=fallbacks,
        close_up_mouth_reliable=close_up_mouth_reliable,
        vendor=vendor or provider,
        model_family=model_family,
        gateway_model_id=gateway_model_id,
        readiness=readiness,
        native_audio_policy=audio_policy,
        production_backend=production_backend,
    )


def _build_catalog() -> tuple[ModelSpec, ...]:
    text = (
        "story_generation",
        "script_doctor",
        "scene_planning",
        "classification",
        "critique",
        "long_context",
    )
    return (
        _m(
            "gpt-6-astra",
            "openai",
            Modality.TEXT,
            caps=text,
            tier=QualityTier.MAX,
            implemented=True,
            implemented_capabilities=text,
            input_modalities=("text",),
            output_modalities=("text",),
            required_credentials=("OPENAI_API_KEY",),
            pricing=GPT6_ASTRA_TEXT,
            notes="GPT-6 flagship for Premium/Max. Same Responses adapter; untested live.",
        ),
        _m(
            "gpt-6-sol",
            "openai",
            Modality.TEXT,
            caps=text,
            tier=QualityTier.PREMIUM,
            implemented=True,
            implemented_capabilities=text,
            input_modalities=("text",),
            output_modalities=("text",),
            required_credentials=("OPENAI_API_KEY",),
            notes="GPT-6 friend-group default (Balanced).",
        ),
        _m(
            "gpt-6-luna",
            "openai",
            Modality.TEXT,
            caps=text,
            implemented=True,
            implemented_capabilities=text,
            input_modalities=("text",),
            output_modalities=("text",),
            required_credentials=("OPENAI_API_KEY",),
            notes="GPT-6 Economy / high-volume.",
        ),
        _m(
            "claude-opus-5-5",
            "anthropic",
            Modality.TEXT,
            caps=(
                "story_writing",
                "script_doctor",
                "dialogue_writing",
                "creative_critique",
                "continuity_review",
                "character_consistency_review",
                "scene_feasibility_review",
                *text,
            ),
            tier=QualityTier.MAX,
            implemented=False,
            implemented_capabilities=(),
            catalog_capabilities=(
                "story_writing",
                "script_doctor",
                "dialogue_writing",
                "creative_critique",
                "continuity_review",
                "character_consistency_review",
                "scene_feasibility_review",
            ),
            input_modalities=("text",),
            output_modalities=("text",),
            required_credentials=("ANTHROPIC_API_KEY",),
            gateway_model_id="claude-opus-5-5",
            model_family="claude-opus",
            vendor="anthropic",
            pricing=CLAUDE_OPUS_55_TEXT,
            notes=(
                "Official Claude API id claude-opus-5-5. Messages API adapter is payload-only; "
                "no HTTP in this phase. Premium script critic."
            ),
        ),
        _m(
            "gpt-5.6-sol",
            "openai",
            Modality.TEXT,
            caps=text,
            tier=QualityTier.PREMIUM,
            notes="Optional higher-tier OpenAI slot",
        ),
        _m(
            "gpt-5.6-terra",
            "openai",
            Modality.TEXT,
            caps=text,
            implemented=True,
            notes="Current writer default in Settings.writer_model",
        ),
        _m(
            "gpt-5.6-luna",
            "openai",
            Modality.TEXT,
            caps=text,
            implemented=True,
            notes="Research/dossier/planner default",
        ),
        _m("claude-sonnet", "anthropic", Modality.TEXT, caps=text, notes="Provider slot"),
        _m("gemini-pro", "google", Modality.TEXT, caps=text, notes="Provider slot"),
        _m(
            "qwen-local",
            "local",
            Modality.TEXT,
            caps=text,
            tier=QualityTier.LOCAL,
            local=True,
            pricing=FREE,
            notes="OpenAI-compatible LOCAL_LLM_BASE_URL",
        ),
        _m(
            "gpt-image-2.5-sunburst",
            "openai",
            Modality.IMAGE,
            caps=(
                "text_to_image",
                "image_reference",
                "multi_reference",
                "character_consistency",
                "editing",
                "high_fidelity_character",
            ),
            tier=QualityTier.PREMIUM,
            implemented=True,
            implemented_capabilities=(
                "text_to_image",
                "image_reference",
                "multi_reference",
                "character_consistency",
                "editing",
            ),
            input_modalities=("text", "image"),
            output_modalities=("image",),
            max_reference_images=16,
            identity_consistency_suitability="high",
            required_credentials=("OPENAI_API_KEY",),
            notes="Highest OpenAI identity/edit path; same adapter as Flare",
        ),
        _m(
            "gpt-image-2.5-flare",
            "openai",
            Modality.IMAGE,
            caps=(
                "text_to_image",
                "image_reference",
                "multi_reference",
                "character_consistency",
                "editing",
                "fast_generation",
            ),
            implemented=True,
            implemented_capabilities=(
                "text_to_image",
                "image_reference",
                "multi_reference",
                "character_consistency",
                "editing",
                "fast_generation",
            ),
            input_modalities=("text", "image"),
            output_modalities=("image",),
            max_reference_images=16,
            identity_consistency_suitability="medium",
            required_credentials=("OPENAI_API_KEY",),
            notes="Fast everyday stills; usage-based $5/$8/$30 per 1M",
            pricing=PricingSpec(
                mode=PriceMode.PER_TOKEN,
                notes="usage-based; per-image list price UNRESOLVED",
                confidence=CostConfidence.ESTIMATED,
            ),
        ),
        _m(
            "gemini-nano-banana",
            "google",
            Modality.IMAGE,
            caps=("text_to_image", "image_reference"),
            notes="Gemini/Nano Banana image slot",
        ),
        _m(
            "higgsfield-soul",
            "higgsfield",
            Modality.IMAGE,
            caps=("text_to_image", "character_consistency", "high_fidelity_character"),
            tier=QualityTier.PREMIUM,
            notes="Soul / Soul ID slot",
        ),
        _m(
            "comfyui-local",
            "local",
            Modality.IMAGE,
            caps=("text_to_image", "image_reference", "editing"),
            tier=QualityTier.LOCAL,
            local=True,
            pricing=FREE,
            notes="LOCAL_IMAGE_BASE_URL",
        ),
        _m(
            "veo-3.1-lite-generate-preview",
            "google",
            Modality.VIDEO,
            caps=("image_to_video", "native_audio"),
            implemented=True,
            async_remote=True,
            pricing=KNOWN_VEO_LITE,
            speed="fast",
            duration_options=(8,),
            min_duration_seconds=8,
            max_duration_seconds=8,
            implemented_capabilities=("image_to_video",),
            catalog_capabilities=("image_to_video", "native_audio"),
            input_modalities=("image", "text"),
            output_modalities=("video",),
            max_reference_images=0,
            aspect_ratios=("16:9", "9:16"),
            resolution_options=("720p",),
            native_audio=True,
            identity_consistency_suitability="start_frame_only",
            required_credentials=("GEMINI_API_KEY",),
            notes="IMPLEMENTED I2V 8s 720p 16:9+9:16. Native audio not TESTED.",
        ),
        _m(
            "veo-3.1-generate-preview",
            "google",
            Modality.VIDEO,
            caps=(
                "image_to_video",
                "text_to_video",
                "native_audio",
                "first_last_frame",
                "reference_images",
                "portrait",
            ),
            tier=QualityTier.PREMIUM,
            aspect_ratios=("16:9", "9:16"),
            native_audio=True,
            notes="Full Veo 3.1 slot. Catalog only; no product HTTP adapter.",
        ),
        _m(
            "veo-3.1-fast",
            "google",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video"),
            speed="fast",
            notes="Catalog only; HTTP contract not implemented here",
        ),
        _m(
            "veo-3.1-standard",
            "google",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video", "native_audio"),
            tier=QualityTier.PREMIUM,
            catalog_capabilities=("image_to_video", "text_to_video", "native_audio"),
            notes="Full Veo 3.1 alias. Catalog only; price UNRESOLVED.",
        ),
        _m(
            "kling-3",
            "higgsfield",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video"),
            adapter_status=AdapterStatus.DOCUMENTED_UNIMPLEMENTED,
            vendor="kling",
            model_family="kling-3",
            notes=(
                "Legacy Kling slot. Prefer documented kling-3.0-* catalog ids. "
                "No HTTP adapter."
            ),
        ),
        _m(
            "kling-2.5-turbo-i2v",
            "higgsfield",
            Modality.VIDEO,
            caps=("image_to_video",),
            adapter_status=AdapterStatus.DOCUMENTED_UNIMPLEMENTED,
            vendor="kling",
            model_family="kling-2.5",
            duration_options=(5, 10),
            notes="Unofficial mirrors list 5/10s I2V; not taken as official schema.",
        ),
        _m(
            "kling-3.0-4k-text-to-video",
            "higgsfield",
            Modality.VIDEO,
            caps=("text_to_video", "native_audio", "portrait"),
            tier=QualityTier.PREMIUM,
            vendor="kling",
            model_family="kling-3.0",
            gateway_model_id="kling-video/v3.0/4k/text-to-video",
            pricing=HF_KLING_4K_T2V,
            min_duration_seconds=3,
            max_duration_seconds=15,
            aspect_ratios=("16:9", "9:16", "1:1"),
            native_audio=True,
            native_audio_policy=NativeAudioPolicy.NATIVE_DIALOGUE_REPLACEABLE,
            required_credentials=("HIGGSFIELD_API_KEY_ID", "HIGGSFIELD_API_KEY_SECRET"),
            notes=(
                "CATALOG_ONLY. POST https://api.higgsfield.ai/kling-video/v3.0/4k/text-to-video "
                "params: sound, prompt, duration 3–15, cfg_scale, multi_shots, aspect_ratio."
            ),
        ),
        _m(
            "kling-3.0-turbo-text-to-video",
            "higgsfield",
            Modality.VIDEO,
            caps=("text_to_video", "portrait"),
            vendor="kling",
            model_family="kling-3.0",
            gateway_model_id="kling-video/v3.0-turbo/text-to-video",
            min_duration_seconds=3,
            max_duration_seconds=15,
            aspect_ratios=("16:9", "9:16", "1:1"),
            resolution_options=("720p", "1080p"),
            required_credentials=("HIGGSFIELD_API_KEY_ID", "HIGGSFIELD_API_KEY_SECRET"),
            notes="CATALOG_ONLY. Documented prompt/duration/resolution/aspect_ratio.",
        ),
        _m(
            "kling-3.0-pro-image-to-video",
            "higgsfield",
            Modality.VIDEO,
            caps=("image_to_video", "native_audio"),
            vendor="kling",
            model_family="kling-3.0",
            gateway_model_id="kling-video/v3.0/pro/image-to-video",
            min_duration_seconds=3,
            max_duration_seconds=15,
            native_audio=True,
            native_audio_policy=NativeAudioPolicy.NATIVE_DIALOGUE_REPLACEABLE,
            required_credentials=("HIGGSFIELD_API_KEY_ID", "HIGGSFIELD_API_KEY_SECRET"),
            notes=(
                "CATALOG_ONLY. image_url required; optional last_image_url, sound, duration 3–15."
            ),
        ),
        _m(
            "kling-3.0-motion-control-pro",
            "higgsfield",
            Modality.VIDEO,
            caps=(
                "motion_controlled_performance",
                "performance_transfer",
                "driving_video",
                "image_to_video",
            ),
            tier=QualityTier.PREMIUM,
            vendor="kling",
            model_family="kling-3.0",
            gateway_model_id="kling-video/v3/motion-control/pro",
            pricing=HF_KLING_MOTION,
            performance_transfer=True,
            input_modalities=("image", "video", "text"),
            output_modalities=("video",),
            required_credentials=("HIGGSFIELD_API_KEY_ID", "HIGGSFIELD_API_KEY_SECRET"),
            notes=(
                "CATALOG_ONLY. POST .../kling-video/v3/motion-control/pro "
                "requires image_url + video_url; keep_original_sound; character_orientation."
            ),
        ),
        _m(
            "seedance",
            "higgsfield",
            Modality.VIDEO,
            caps=("text_to_video",),
            adapter_status=AdapterStatus.DOCUMENTED_UNIMPLEMENTED,
            vendor="bytedance",
            model_family="seedance-2.0",
            notes="Legacy Seedance 2.0 T2V slot. Prefer seedance-2.5-* catalog ids.",
        ),
        _m(
            "seedance-2.5-text-to-video",
            "higgsfield",
            Modality.VIDEO,
            caps=("text_to_video", "native_audio", "portrait"),
            tier=QualityTier.PREMIUM,
            vendor="bytedance",
            model_family="seedance-2.5",
            gateway_model_id="bytedance/seedance-2.5/text-to-video",
            pricing=HF_SEEDANCE_25_GEN,
            min_duration_seconds=4,
            max_duration_seconds=30,
            aspect_ratios=("16:9", "4:3", "1:1", "3:4", "9:16", "21:9"),
            resolution_options=("480p", "720p"),
            native_audio=True,
            native_audio_policy=NativeAudioPolicy.NATIVE_DIALOGUE_REPLACEABLE,
            required_credentials=("HIGGSFIELD_API_KEY_ID", "HIGGSFIELD_API_KEY_SECRET"),
            notes=(
                "CATALOG_ONLY. Documented: prompt, duration 4–30, resolution 480p/720p, "
                "aspect_ratio incl 9:16, output_format mp4/mov, generate_audio."
            ),
        ),
        _m(
            "seedance-2.5-image-to-video",
            "higgsfield",
            Modality.VIDEO,
            caps=("image_to_video", "native_audio", "first_last_frame"),
            tier=QualityTier.PREMIUM,
            vendor="bytedance",
            model_family="seedance-2.5",
            gateway_model_id="bytedance/seedance-2.5/image-to-video",
            pricing=HF_SEEDANCE_25_GEN,
            min_duration_seconds=4,
            max_duration_seconds=30,
            max_reference_images=2,
            resolution_options=("480p", "720p"),
            native_audio=True,
            native_audio_policy=NativeAudioPolicy.NATIVE_DIALOGUE_REPLACEABLE,
            required_credentials=("HIGGSFIELD_API_KEY_ID", "HIGGSFIELD_API_KEY_SECRET"),
            notes=(
                "CATALOG_ONLY. image_url required; optional prompt, end_image_url, "
                "duration 4–30, generate_audio. No invented extra refs."
            ),
        ),
        _m(
            "seedance-2.5-reference-to-video",
            "higgsfield",
            Modality.VIDEO,
            caps=(
                "reference_to_video",
                "multi_reference",
                "native_audio",
                "portrait",
            ),
            tier=QualityTier.PREMIUM,
            vendor="bytedance",
            model_family="seedance-2.5",
            gateway_model_id="bytedance/seedance-2.5/reference-to-video",
            pricing=HF_SEEDANCE_25_GEN,
            min_duration_seconds=4,
            max_duration_seconds=30,
            aspect_ratios=("16:9", "9:16"),
            resolution_options=("480p", "720p"),
            native_audio=True,
            native_audio_policy=NativeAudioPolicy.NATIVE_DIALOGUE_REPLACEABLE,
            identity_consistency_suitability="multi_reference_candidate",
            required_credentials=("HIGGSFIELD_API_KEY_ID", "HIGGSFIELD_API_KEY_SECRET"),
            notes=(
                "Documented subscribe input: prompt, duration, image_urls, video_urls, "
                "audio_urls, resolution 480p/720p, aspect_ratio incl 9:16, bitrate_mode, "
                "generate_audio. Friend Group uses 720p 9:16."
            ),
        ),
        _m(
            "seedance-2.5-video-edit",
            "higgsfield",
            Modality.VIDEO,
            caps=("video_edit", "video_to_video", "native_audio"),
            tier=QualityTier.PREMIUM,
            vendor="bytedance",
            model_family="seedance-2.5",
            gateway_model_id="bytedance/seedance-2.5/video-edit",
            pricing=HF_SEEDANCE_25_EDIT,
            min_duration_seconds=4,
            max_duration_seconds=30,
            native_audio=True,
            native_audio_policy=NativeAudioPolicy.NATIVE_DIALOGUE_REPLACEABLE,
            required_credentials=("HIGGSFIELD_API_KEY_ID", "HIGGSFIELD_API_KEY_SECRET"),
            notes=(
                "CATALOG_ONLY. Documented: prompt, video_url, resolution, bitrate_mode, "
                "generate_audio."
            ),
        ),
        _m(
            "seedance-2.5-video-extend",
            "higgsfield",
            Modality.VIDEO,
            caps=("video_extend", "video_to_video", "native_audio"),
            tier=QualityTier.PREMIUM,
            vendor="bytedance",
            model_family="seedance-2.5",
            gateway_model_id="bytedance/seedance-2.5/video-extend",
            pricing=HF_SEEDANCE_25_EDIT,
            min_duration_seconds=4,
            max_duration_seconds=30,
            native_audio=True,
            native_audio_policy=NativeAudioPolicy.NATIVE_DIALOGUE_REPLACEABLE,
            required_credentials=("HIGGSFIELD_API_KEY_ID", "HIGGSFIELD_API_KEY_SECRET"),
            notes=(
                "CATALOG_ONLY. Documented: prompt, duration, video_url, resolution, "
                "bitrate_mode, generate_audio."
            ),
        ),
        _m(
            "wan",
            "higgsfield",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video"),
            notes="Hosted Wan family slot",
        ),
        _m(
            "minimax-hailuo",
            "higgsfield",
            Modality.VIDEO,
            caps=("image_to_video",),
            notes="MiniMax/Hailuo slot",
        ),
        _m(
            "runway-gen-4.5",
            "runway",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video"),
            tier=QualityTier.PREMIUM,
            implemented=True,
            async_remote=True,
            pricing=KNOWN_GEN45,
            duration_options=tuple(range(2, 11)),
            min_duration_seconds=2,
            max_duration_seconds=10,
            implemented_capabilities=("image_to_video", "text_to_video"),
            input_modalities=("image", "text"),
            output_modalities=("video",),
            close_up_mouth_reliable=False,
            required_credentials=("RUNWAY_API_KEY",),
            notes="Premium hero/complex motion candidate. Not auto for every Premium shot.",
        ),
        _m(
            "runway-act-two",
            "runway",
            Modality.VIDEO,
            caps=("performance_transfer", "driving_video", "lip_sync", "dialogue"),
            tier=QualityTier.PREMIUM,
            implemented=True,
            async_remote=True,
            pricing=KNOWN_ACT_TWO,
            min_duration_seconds=3,
            max_duration_seconds=30,
            notes="POST /v1/character_performance model act_two; optional, never auto-required",
            manual_input_required=True,
        ),
        _m(
            "higgsfield-genjutsu",
            "higgsfield",
            Modality.VIDEO,
            caps=(
                "performance_transfer",
                "driving_video",
                "motion_controlled_performance",
            ),
            tier=QualityTier.PREMIUM,
            adapter_status=AdapterStatus.DOCUMENTED_UNIMPLEMENTED,
            vendor="higgsfield",
            model_family="genjutsu",
            gateway_model_id="higgsfield/genjutsu/motion-transfer/v1.0",
            pricing=HF_GENJUTSU,
            min_duration_seconds=1,
            max_duration_seconds=30,
            performance_transfer=True,
            resolution_options=("480p", "720p", "1080p"),
            required_credentials=("HIGGSFIELD_API_KEY_ID", "HIGGSFIELD_API_KEY_SECRET"),
            notes=(
                "Documented subscribe path higgsfield/genjutsu/motion-transfer/v1.0 "
                "(prompt, video_url, image_urls, resolution). No product HTTP POST yet."
            ),
            manual_input_required=True,
        ),
        _m(
            "higgsfield-motion-designer",
            "higgsfield",
            Modality.VIDEO,
            caps=(
                "post_production",
                "motion_graphics",
                "titles",
                "kinetic_subtitles",
            ),
            vendor="higgsfield",
            model_family="motion-designer",
            production_backend=ProductionBackend.OPTIONAL_PRODUCTION_BACKEND,
            required_credentials=(),
            notes=(
                "OPTIONAL_PRODUCTION_BACKEND. After Effects plugin + MCP "
                "bridge.higgsfield.ai/mcp. Not ordinary cinematic I2V. "
                "Not required for MVP; local FFmpeg first."
            ),
        ),
        _m(
            "audio-driven-lipsync",
            "unassigned",
            Modality.VIDEO,
            caps=(
                "accepts_target_audio",
                "lip_sync",
                "facial_motion",
                "head_motion",
                "body_motion",
                "character_consistency",
                "dialogue",
            ),
            tier=QualityTier.PREMIUM,
            notes=(
                "Placeholder slot for a documented audio-driven dialogue adapter. "
                "No network payload until an official schema exists."
            ),
        ),
        _m(
            "ltx-local",
            "local",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "hunyuan-video-local",
            "local",
            Modality.VIDEO,
            caps=("text_to_video", "image_to_video"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "hunyuan-avatar-local",
            "local",
            Modality.VIDEO,
            caps=("lip_sync", "dialogue", "driving_video"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "wan-local",
            "local",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "eleven-v3",
            "elevenlabs",
            Modality.TTS,
            caps=("turkish", "expressiveness", "voice_cloning", "style_instruction"),
            tier=QualityTier.PREMIUM,
            implemented=True,
            pricing=KNOWN_ELEVEN_TTS,
            implemented_capabilities=("turkish", "expressiveness"),
            dialogue=True,
            required_credentials=("ELEVENLABS_API_KEY",),
            notes="Premium/Max dialogue. Adapter exists; not on Telegram generate yet.",
        ),
        _m(
            "eleven-multilingual",
            "elevenlabs",
            Modality.TTS,
            caps=("turkish", "long_form"),
        ),
        _m(
            "gpt-4o-mini-tts",
            "openai",
            Modality.TTS,
            caps=("turkish", "style_instruction", "long_form"),
            implemented=True,
            pricing=KNOWN_TTS_TEXT,
        ),
        _m("gemini-tts", "google", Modality.TTS, caps=("turkish",)),
        _m(
            "chatterbox-multilingual",
            "local",
            Modality.TTS,
            caps=("turkish", "local", "expressiveness"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "lyria-3.5",
            "google",
            Modality.MUSIC,
            caps=("instrumental", "image_conditioning"),
            implemented=True,
            pricing=KNOWN_LYRIA,
        ),
        _m(
            "eleven-music",
            "elevenlabs",
            Modality.MUSIC,
            caps=("instrumental", "lyrics", "section_control", "inpainting"),
            tier=QualityTier.PREMIUM,
            implemented=True,
            pricing=KNOWN_ELEVEN_MUSIC,
            notes="POST /v1/music; Birko V2 still reuses cached Lyria by default",
        ),
        _m(
            "stable-audio",
            "stability",
            Modality.MUSIC,
            caps=("instrumental", "duration_control"),
        ),
        _m(
            "ace-step-local",
            "local",
            Modality.MUSIC,
            caps=("instrumental", "local"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "yue-local",
            "local",
            Modality.MUSIC,
            caps=("instrumental", "lyrics", "local"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "local-library",
            "local",
            Modality.SFX,
            caps=("generic",),
            implemented=True,
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "procedural-sfx",
            "local",
            Modality.SFX,
            caps=("generic", "foley"),
            implemented=True,
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "eleven-sfx",
            "elevenlabs",
            Modality.SFX,
            caps=("hero",),
            tier=QualityTier.PREMIUM,
            implemented=True,
            pricing=KNOWN_ELEVEN_SFX,
            notes="POST /v1/sound-generation eleven_text_to_sound_v2; HERO_SFX only",
        ),
        _m("stable-audio-sfx", "stability", Modality.SFX, caps=("hero", "ambience")),
        _m(
            "audioldm2-local",
            "local",
            Modality.SFX,
            caps=("generic", "local"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "whisper-1",
            "openai",
            Modality.ALIGNMENT,
            caps=("word_timestamps", "language_support"),
            implemented=True,
            pricing=KNOWN_WHISPER,
        ),
        _m(
            "openai-transcription",
            "openai",
            Modality.ALIGNMENT,
            caps=("word_timestamps",),
            notes="Newer transcription interface slot",
        ),
        _m(
            "eleven-scribe",
            "elevenlabs",
            Modality.ALIGNMENT,
            caps=("word_timestamps", "speaker_diarization"),
        ),
        _m(
            "faster-whisper-local",
            "local",
            Modality.ALIGNMENT,
            caps=("word_timestamps", "local", "language_support"),
            local=True,
            pricing=FREE,
            implemented=False,
            tier=QualityTier.LOCAL,
        ),
    )


@lru_cache
def model_catalog() -> tuple[ModelSpec, ...]:
    return _build_catalog()


def models_by_id() -> dict[str, ModelSpec]:
    return {item.model_id: item for item in model_catalog()}


def models_for(modality: Modality) -> list[ModelSpec]:
    return [item for item in model_catalog() if item.modality is modality]


def get_model(model_id: str) -> ModelSpec | None:
    return models_by_id().get(model_id)
