from __future__ import annotations

from functools import lru_cache

from docprod.providers.pricing import (
    ELEVEN_MUSIC_USD_PER_MINUTE,
    ELEVEN_SFX_USD_PER_MINUTE,
    ELEVEN_V3_USD_PER_1K_CHARS,
    LYRIA_35_USD_PER_SONG,
    PRICING_AS_OF,
    RUNWAY_ACT_TWO_USD_PER_SEC,
    RUNWAY_GEN45_USD_PER_SEC,
    VEO_LITE_720P_USD_PER_SEC,
)
from docprod.quality.enums import AdapterStatus, CostConfidence, Modality, PriceMode, QualityTier
from docprod.quality.specs import ModelSpec, PricingSpec

KNOWN_TTS_TEXT = PricingSpec(
    mode=PriceMode.PER_TOKEN,
    value=0.60 / 1_000_000,
    unit="text_token_in",
    notes="$0.60/1M text in; audio-out $12/1M when usage present",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="OpenAI TTS usage",
)
KNOWN_WHISPER = PricingSpec(
    mode=PriceMode.PER_MINUTE,
    value=0.006,
    unit="minute",
    notes="OpenAI Whisper $0.006/min",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="OpenAI audio API",
)
KNOWN_VEO_LITE = PricingSpec(
    mode=PriceMode.PER_SECOND,
    value=VEO_LITE_720P_USD_PER_SEC,
    unit="second",
    notes="Veo 3.1 Lite 720p known unit price",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="Google Veo Lite",
)
KNOWN_LYRIA = PricingSpec(
    mode=PriceMode.PER_REQUEST,
    value=LYRIA_35_USD_PER_SONG,
    unit="song",
    notes="Lyria Interactions $0.08/song",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="Google Lyria",
)
KNOWN_GEN45 = PricingSpec(
    mode=PriceMode.PER_SECOND,
    value=RUNWAY_GEN45_USD_PER_SEC,
    unit="second",
    notes="12 credits/s × $0.01",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="https://docs.dev.runwayml.com/guides/pricing/",
)
KNOWN_ACT_TWO = PricingSpec(
    mode=PriceMode.PER_SECOND,
    value=RUNWAY_ACT_TWO_USD_PER_SEC,
    unit="second",
    notes="5 credits/s × $0.01; driving 3–30s",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="https://docs.dev.runwayml.com/guides/pricing/",
)
KNOWN_ELEVEN_TTS = PricingSpec(
    mode=PriceMode.PER_CHARACTER,
    value=ELEVEN_V3_USD_PER_1K_CHARS / 1000.0,
    unit="character",
    notes="$0.10 / 1K characters",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="https://elevenlabs.io/pricing/api",
)
KNOWN_ELEVEN_SFX = PricingSpec(
    mode=PriceMode.PER_MINUTE,
    value=ELEVEN_SFX_USD_PER_MINUTE,
    unit="minute",
    notes="$0.12 / minute",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="https://elevenlabs.io/pricing/api",
)
KNOWN_ELEVEN_MUSIC = PricingSpec(
    mode=PriceMode.PER_MINUTE,
    value=ELEVEN_MUSIC_USD_PER_MINUTE,
    unit="minute",
    notes="$0.15 / minute",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
    source_note="https://elevenlabs.io/pricing/api",
)
FREE = PricingSpec(
    mode=PriceMode.FREE,
    value=0.0,
    unit="call",
    confidence=CostConfidence.KNOWN,
    pricing_as_of=PRICING_AS_OF,
)
UNKNOWN = PricingSpec(mode=PriceMode.UNKNOWN, confidence=CostConfidence.UNRESOLVED)


def _m(
    model_id: str,
    provider: str,
    modality: Modality,
    *,
    caps: tuple[str, ...] = (),
    tier: QualityTier = QualityTier.STANDARD,
    speed: str = "unknown",
    pricing: PricingSpec | None = None,
    implemented: bool = False,
    adapter_status: AdapterStatus | None = None,
    async_remote: bool = False,
    local: bool = False,
    notes: str = "",
    display: str = "",
    duration_options: tuple[int, ...] = (),
    min_duration_seconds: float | None = None,
    max_duration_seconds: float | None = None,
    manual_input_required: bool = False,
) -> ModelSpec:
    status = adapter_status
    if status is None:
        status = AdapterStatus.IMPLEMENTED if implemented else AdapterStatus.CATALOG_ONLY
    return ModelSpec(
        model_id=model_id,
        provider=provider,
        modality=modality,
        display_name=display or model_id,
        capabilities=caps,
        quality_tier=tier,
        speed_tier=speed,
        pricing=pricing or UNKNOWN,
        implemented=implemented,
        adapter_status=status,
        async_remote=async_remote,
        local=local,
        notes=notes,
        duration_options=duration_options,
        min_duration_seconds=min_duration_seconds,
        max_duration_seconds=max_duration_seconds,
        manual_input_required=manual_input_required,
    )


def _build_catalog() -> tuple[ModelSpec, ...]:
    text = (
        "story_generation",
        "script_doctor",
        "scene_planning",
        "classification",
        "critique",
        "long_context",
    )
    return (
        _m(
            "gpt-5.6-sol",
            "openai",
            Modality.TEXT,
            caps=text,
            tier=QualityTier.PREMIUM,
            notes="Optional higher-tier OpenAI slot",
        ),
        _m(
            "gpt-5.6-terra",
            "openai",
            Modality.TEXT,
            caps=text,
            implemented=True,
            notes="Current writer default in Settings.writer_model",
        ),
        _m(
            "gpt-5.6-luna",
            "openai",
            Modality.TEXT,
            caps=text,
            implemented=True,
            notes="Research/dossier/planner default",
        ),
        _m("claude-sonnet", "anthropic", Modality.TEXT, caps=text, notes="Provider slot"),
        _m("gemini-pro", "google", Modality.TEXT, caps=text, notes="Provider slot"),
        _m(
            "qwen-local",
            "local",
            Modality.TEXT,
            caps=text,
            tier=QualityTier.LOCAL,
            local=True,
            pricing=FREE,
            notes="OpenAI-compatible LOCAL_LLM_BASE_URL",
        ),
        _m(
            "gpt-image-2.5-sunburst",
            "openai",
            Modality.IMAGE,
            caps=(
                "text_to_image",
                "image_reference",
                "multi_reference",
                "character_consistency",
                "editing",
                "high_fidelity_character",
            ),
            tier=QualityTier.PREMIUM,
            notes="Preferred for character refs when configured; list price UNRESOLVED",
        ),
        _m(
            "gpt-image-2.5-flare",
            "openai",
            Modality.IMAGE,
            caps=(
                "text_to_image",
                "image_reference",
                "multi_reference",
                "character_consistency",
                "editing",
                "fast_generation",
            ),
            implemented=True,
            notes="Current default timeline stills; usage-based $5/$8/$30 per 1M",
            pricing=PricingSpec(
                mode=PriceMode.PER_TOKEN,
                notes="usage-based; per-image list price UNRESOLVED",
                confidence=CostConfidence.ESTIMATED,
            ),
        ),
        _m(
            "gemini-nano-banana",
            "google",
            Modality.IMAGE,
            caps=("text_to_image", "image_reference"),
            notes="Gemini/Nano Banana image slot",
        ),
        _m(
            "higgsfield-soul",
            "higgsfield",
            Modality.IMAGE,
            caps=("text_to_image", "character_consistency", "high_fidelity_character"),
            tier=QualityTier.PREMIUM,
            notes="Soul / Soul ID slot",
        ),
        _m(
            "comfyui-local",
            "local",
            Modality.IMAGE,
            caps=("text_to_image", "image_reference", "editing"),
            tier=QualityTier.LOCAL,
            local=True,
            pricing=FREE,
            notes="LOCAL_IMAGE_BASE_URL",
        ),
        _m(
            "veo-3.1-lite-generate-preview",
            "google",
            Modality.VIDEO,
            caps=("image_to_video", "native_audio"),
            implemented=True,
            async_remote=True,
            pricing=KNOWN_VEO_LITE,
            speed="fast",
            duration_options=(8,),
            min_duration_seconds=8,
            max_duration_seconds=8,
            notes="Implemented Veo 3.1 Lite I2V 8s 720p",
        ),
        _m(
            "veo-3.1-fast",
            "google",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video"),
            speed="fast",
            notes="Catalog only; HTTP contract not implemented here",
        ),
        _m(
            "veo-3.1-standard",
            "google",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video", "native_audio"),
            tier=QualityTier.PREMIUM,
            notes="Catalog only; price UNRESOLVED",
        ),
        _m(
            "kling-3",
            "higgsfield",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video"),
            adapter_status=AdapterStatus.DOCUMENTED_UNIMPLEMENTED,
            notes=(
                "Kling I2V body is not in docs.higgsfield.ai public index "
                "(console-discovered schemas only)."
            ),
        ),
        _m(
            "kling-2.5-turbo-i2v",
            "higgsfield",
            Modality.VIDEO,
            caps=("image_to_video",),
            adapter_status=AdapterStatus.DOCUMENTED_UNIMPLEMENTED,
            duration_options=(5, 10),
            notes="Unofficial mirrors list 5/10s I2V; not taken as official schema.",
        ),
        _m(
            "seedance",
            "higgsfield",
            Modality.VIDEO,
            caps=("text_to_video",),
            adapter_status=AdapterStatus.DOCUMENTED_UNIMPLEMENTED,
            notes=(
                "Official blog documents Seedance 2.0 T2V only; I2V schema unpublished."
            ),
        ),
        _m(
            "wan",
            "higgsfield",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video"),
            notes="Hosted Wan family slot",
        ),
        _m(
            "minimax-hailuo",
            "higgsfield",
            Modality.VIDEO,
            caps=("image_to_video",),
            notes="MiniMax/Hailuo slot",
        ),
        _m(
            "runway-gen-4.5",
            "runway",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video"),
            tier=QualityTier.PREMIUM,
            implemented=True,
            async_remote=True,
            pricing=KNOWN_GEN45,
            duration_options=tuple(range(2, 11)),
            min_duration_seconds=2,
            max_duration_seconds=10,
            notes="POST /v1/image_to_video model gen4.5 — docs.dev.runwayml.com",
        ),
        _m(
            "runway-act-two",
            "runway",
            Modality.VIDEO,
            caps=("performance_transfer", "driving_video", "lip_sync", "dialogue"),
            tier=QualityTier.PREMIUM,
            implemented=True,
            async_remote=True,
            pricing=KNOWN_ACT_TWO,
            min_duration_seconds=3,
            max_duration_seconds=30,
            notes="POST /v1/character_performance model act_two; optional, never auto-required",
            manual_input_required=True,
        ),
        _m(
            "higgsfield-genjutsu",
            "higgsfield",
            Modality.VIDEO,
            caps=("performance_transfer", "driving_video"),
            tier=QualityTier.PREMIUM,
            adapter_status=AdapterStatus.DOCUMENTED_UNIMPLEMENTED,
            min_duration_seconds=3,
            max_duration_seconds=30,
            notes="Product page only; no public REST body. Preflight uses 3–30s / 30 refs.",
            manual_input_required=True,
        ),
        _m(
            "audio-driven-lipsync",
            "unassigned",
            Modality.VIDEO,
            caps=(
                "accepts_target_audio",
                "lip_sync",
                "facial_motion",
                "head_motion",
                "body_motion",
                "character_consistency",
                "dialogue",
            ),
            tier=QualityTier.PREMIUM,
            notes=(
                "Placeholder slot for a documented audio-driven dialogue adapter. "
                "No network payload until an official schema exists."
            ),
        ),
        _m(
            "ltx-local",
            "local",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "hunyuan-video-local",
            "local",
            Modality.VIDEO,
            caps=("text_to_video", "image_to_video"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "hunyuan-avatar-local",
            "local",
            Modality.VIDEO,
            caps=("lip_sync", "dialogue", "driving_video"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "wan-local",
            "local",
            Modality.VIDEO,
            caps=("image_to_video", "text_to_video"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "eleven-v3",
            "elevenlabs",
            Modality.TTS,
            caps=("turkish", "expressiveness", "voice_cloning", "style_instruction"),
            tier=QualityTier.PREMIUM,
            implemented=True,
            pricing=KNOWN_ELEVEN_TTS,
            notes="POST /v1/text-to-speech/{voice_id} model_id eleven_v3",
        ),
        _m(
            "eleven-multilingual",
            "elevenlabs",
            Modality.TTS,
            caps=("turkish", "long_form"),
        ),
        _m(
            "gpt-4o-mini-tts",
            "openai",
            Modality.TTS,
            caps=("turkish", "style_instruction", "long_form"),
            implemented=True,
            pricing=KNOWN_TTS_TEXT,
        ),
        _m("gemini-tts", "google", Modality.TTS, caps=("turkish",)),
        _m(
            "chatterbox-multilingual",
            "local",
            Modality.TTS,
            caps=("turkish", "local", "expressiveness"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "lyria-3.5",
            "google",
            Modality.MUSIC,
            caps=("instrumental", "image_conditioning"),
            implemented=True,
            pricing=KNOWN_LYRIA,
        ),
        _m(
            "eleven-music",
            "elevenlabs",
            Modality.MUSIC,
            caps=("instrumental", "lyrics", "section_control", "inpainting"),
            tier=QualityTier.PREMIUM,
            implemented=True,
            pricing=KNOWN_ELEVEN_MUSIC,
            notes="POST /v1/music; Birko V2 still reuses cached Lyria by default",
        ),
        _m(
            "stable-audio",
            "stability",
            Modality.MUSIC,
            caps=("instrumental", "duration_control"),
        ),
        _m(
            "ace-step-local",
            "local",
            Modality.MUSIC,
            caps=("instrumental", "local"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "yue-local",
            "local",
            Modality.MUSIC,
            caps=("instrumental", "lyrics", "local"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "local-library",
            "local",
            Modality.SFX,
            caps=("generic",),
            implemented=True,
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "procedural-sfx",
            "local",
            Modality.SFX,
            caps=("generic", "foley"),
            implemented=True,
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "eleven-sfx",
            "elevenlabs",
            Modality.SFX,
            caps=("hero",),
            tier=QualityTier.PREMIUM,
            implemented=True,
            pricing=KNOWN_ELEVEN_SFX,
            notes="POST /v1/sound-generation eleven_text_to_sound_v2; HERO_SFX only",
        ),
        _m("stable-audio-sfx", "stability", Modality.SFX, caps=("hero", "ambience")),
        _m(
            "audioldm2-local",
            "local",
            Modality.SFX,
            caps=("generic", "local"),
            local=True,
            pricing=FREE,
            tier=QualityTier.LOCAL,
        ),
        _m(
            "whisper-1",
            "openai",
            Modality.ALIGNMENT,
            caps=("word_timestamps", "language_support"),
            implemented=True,
            pricing=KNOWN_WHISPER,
        ),
        _m(
            "openai-transcription",
            "openai",
            Modality.ALIGNMENT,
            caps=("word_timestamps",),
            notes="Newer transcription interface slot",
        ),
        _m(
            "eleven-scribe",
            "elevenlabs",
            Modality.ALIGNMENT,
            caps=("word_timestamps", "speaker_diarization"),
        ),
        _m(
            "faster-whisper-local",
            "local",
            Modality.ALIGNMENT,
            caps=("word_timestamps", "local", "language_support"),
            local=True,
            pricing=FREE,
            implemented=False,
            tier=QualityTier.LOCAL,
        ),
    )


@lru_cache
def model_catalog() -> tuple[ModelSpec, ...]:
    return _build_catalog()


def models_by_id() -> dict[str, ModelSpec]:
    return {item.model_id: item for item in model_catalog()}


def models_for(modality: Modality) -> list[ModelSpec]:
    return [item for item in model_catalog() if item.modality is modality]


def get_model(model_id: str) -> ModelSpec | None:
    return models_by_id().get(model_id)
